[phases.setup]
nixPkgs = ["nodejs_22", "pnpm", "openssl"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm db:generate", "NODE_ENV=production pnpm build"]

[start]
cmd = "pnpm db:migrate:deploy && pnpm start"

