[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm db:generate && NODE_ENV=production pnpm build"

[deploy]
startCommand = "pnpm db:migrate:deploy && pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
# Use pnpm instead of npm
installCommand = "pnpm install"

